spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/walletdb
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Tự động cập nhật schema (development only)
    show-sql: true # Hiển thị SQL trên console (development only)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect 
        format_sql: true 
